In [3]:
import torch
import numpy as np

How to create tensor from list data

In [5]:
data = [
    [1, 2],
    [3, 4]
]

tensors = torch.tensor(data)

In [7]:
type(tensors)

torch.Tensor

This can also be created from numpy data

In [11]:
np_array = [
    np.arange(3),
    np.arange(3, 6)
]

np_array

[array([0, 1, 2]), array([3, 4, 5])]

In [13]:
tensor_np = torch.tensor(np_array)

tensor_np

tensor([[0, 1, 2],
        [3, 4, 5]], dtype=torch.int32)

Checking tensor's shape, dimension (ndim), and data type (dtype)

In [20]:
tensor_np.shape

torch.Size([2, 3])

In [22]:
tensor_np.ndim

2

In [24]:
type(tensor_np), tensor_np.dtype

(torch.Tensor, torch.int32)

Basic Operations on Tensor

In [25]:
ten1 = torch.tensor(np.arange(1, 4))
ten2 = torch.tensor(np.arange(4, 7))

ten1 + ten2

tensor([5, 7, 9], dtype=torch.int32)

In [28]:
# add two tensors using add() method

torch.add(ten1, ten2)

tensor([5, 7, 9], dtype=torch.int32)

In [29]:
# subtract ten2 from ten1 using sub()/subtract() method

torch.sub(ten1, ten2)

tensor([-3, -3, -3], dtype=torch.int32)

Multiplying scalar with vector

In [31]:
10 * ten1

tensor([10, 20, 30], dtype=torch.int32)

The following are very important operation in Deep Learning - Matrix Multiplication

~ Rules of Matrix Multiplication

- When multiplying two tensors or Matrices together, the column of the first tensor must be equal to the row of the second tensor

Note: (3, 2) * (3, 2) is wrong,
      (4, 3) * (3, 2) gives (4, 2)

In [32]:
torch.matmul(ten1, ten2) # this results to scalar

tensor(32, dtype=torch.int32)

In [35]:
matrix_4_by_3 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

In [36]:
matrix_4_by_3.shape

torch.Size([4, 3])

In [38]:
matrix_3_by_2 = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [40]:
matrix_3_by_2.shape

torch.Size([3, 2])

Checking out the above rule for matrices multiplication

In [42]:
mat_result = torch.matmul(matrix_4_by_3, matrix_3_by_2)

In [43]:
mat_result

tensor([[ 22,  28],
        [ 49,  64],
        [ 76, 100],
        [103, 136]])

In [44]:
mat_result.shape

torch.Size([4, 2])

Aside matmul() method, you can also use mm() method which is a short for torch.matmul()

In [47]:
torch.mm(matrix_4_by_3, matrix_3_by_2) # .shape

tensor([[ 22,  28],
        [ 49,  64],
        [ 76, 100],
        [103, 136]])

Tensor can be transpose using matrix_name.T

In [48]:
matrix_4_by_3

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [49]:
matrix_4_by_3.T

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])

Or use torch.t(matrix_name)

In [50]:
torch.t(matrix_4_by_3)

tensor([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])

Extra Pytorch Operations Based on Tensor

- Zeroes
- Ones
- Random
- Full

In [51]:
# The following creates zero-elements matrix of specify dimension

tensor_zeroes = torch.zeros((3, 3))

tensor_zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [52]:
# The following creates one-elements matrix of the specify dimension

tensor_ones = torch.ones((3, 3))

tensor_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [53]:
# The following creates matrix numbers that are between the specified range and also if randn() method this produces both +ve and -ve but if rand() this only produces +ve numbers through out

tensorRandomN = torch.randn((3, 3)) # Includes negative tensors

tensorRandomN

tensor([[ 0.1837,  1.0460,  1.1349],
        [ 0.0415, -0.2630,  1.2239],
        [ 1.1065, -0.0370,  1.3403]])

In [54]:
tensorRandom = torch.rand((3, 3)) # Includes negative tensors

tensorRandom

tensor([[0.5579, 0.3702, 0.5271],
        [0.9258, 0.8823, 0.6497],
        [0.5287, 0.6978, 0.5248]])

In [55]:
customFill = torch.full((3, 3), 5)

customFill

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [56]:
initialFill = torch.full((3, 3), 0.01)

initialFill

tensor([[0.0100, 0.0100, 0.0100],
        [0.0100, 0.0100, 0.0100],
        [0.0100, 0.0100, 0.0100]])

### Quickstart

Install Torchvision, the torchvision package consists of popular datasets, model architectures, and common image transformations for computer vision.

    pip install torchvision --no-deps